services:
  strangeverse:
    image: ghcr.io/abrahan-eagle/strangeverse:latest
    # 加速镜像（如拉取缓慢可替换上方地址）
    # image: ghcr.nju.edu.cn/abrahan-eagle/strangeverse:latest
    container_name: strangeverse
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/backend/uploads